### ISSUE TITLE
Connect to ELASTIC_APM_SERVER_URL fails if contains a backslash at the end

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-go#660] opened 2019-10-17 08:03 UTC
**Describe the bug**

If you set ELASTIC_APM_SERVER_URL to “http://apm-server:8200/”, it would not work, for some reason, you have to remove the final backslash and set it to “http://apm-server:8200" then it works.

**To Reproduce**
1. Start Elastic Stack with APM
2. start the Opbeans-go with the ELASTIC_APM_SERVER_URL environment variable set to “http://apm-server:8200/”
3. Connect to the Opbeans-go to generate transactions
4. Check that there is nothing on the APM UI

**Expected behavior**
After generating some transactions on the Opbeans-go those should be sent to the APM server but are not.

**Comment by axw** [comment] 2019-10-17 08:08
I already fixed this :) Duplicate of https://github.com/elastic/apm-agent-go/issues/657

**Closed by axw** 2019-10-17 08:08 UTC
Labels: bug
