### ISSUE TITLE
go-sysinfo checksum mismatch due to floating version 

### ISSUE THREAD

**Issue by fatmcgav** [elastic/apm-agent-go#529] opened 2019-05-14 09:48 UTC
**Describe the bug**
Upon attempting to run `go mod vendor` for a project that requires `apm-go 1.2.0`, I hit a checksum mismatch error:

```
verifying github.com/elastic/go-sysinfo@v0.0.0-20190103140604-e68552284485: checksum mismatch
        downloaded: h1:/mUt2Qiz4aUNSZCYio6WlxZG7N5rlCDs46NuZppJLUc=
        go.sum:     h1:k9Ac5c19ZDF7XOktjJP50LTn3a9+HPUONWXyqT6Xt7M=
```

This dep is coming from here:
https://github.com/elastic/apm-agent-go/blob/47cc289609d7000794e858f84652c5ddbe17e623/go.mod#L6

It appears that there are now some 'tagged' releases of `go-sysinfo`, so should just be a case of switching `go-sysinfo` to a fixed release.

**Comment by axw** [comment] 2019-05-22 05:10
What version of Go are you using? There have been some bugs in the Go toolchain related to checksum verification. I'd start looking there, since our CI should have complained by now about a mismatch.

**Comment by fatmcgav** [comment] 2019-05-22 07:54
@axw i was using `go 1.12`, unfortunately I don't know the point release and I'm on leave atm...

**Comment by axw** [comment] 2019-05-22 08:02
@fatmcgav enjoy your leave, hit me up when you're back and we can work through it together :)

**Comment by axw** [comment] 2019-06-09 06:11
@fatmcgav As I can't see any issues myself, I'm closing this. If you reproduce the issue, please reopen with the steps.

**Closed by axw** 2019-06-09 06:11 UTC
Labels: [zube]: In Progress
