### ISSUE TITLE
Problem with init

### ISSUE THREAD

**Issue by berni69** [elastic/apm-agent-go#617] opened 2019-08-26 20:21 UTC
Hi,

First of all thanks the community for this software, I would like to know how to configure this package using dotenv env vars. I'm using  the module for mux ("go.elastic.co/apm/module/apmgorilla")

I tried to load the environment on the main  function as follows:

```go
import (
	"github.com/gorilla/mux"
	"github.com/joho/godotenv"
	"go.elastic.co/apm/module/apmgorilla"
       ....
)

func main() {
	err := godotenv.Load()
	if err != nil {
		log.Warning("Error loading .env file")
	}

	/* Starting new Router */
	router := mux.NewRouter()
	apmgorilla.Instrument(router)
	router.Use(apmgorilla.Middleware())
	router.HandleFunc("/hello", helloWorld).Methods("GET")
	addressPort := utils.GetEnv("ADDRESS_PORT", ":8000")
	log.Fatal(http.ListenAndServe(addressPort, router))

}
```
My .env looks like:
```bash
ADDRESS_PORT=0.0.0.0:8000
ELASTIC_APM_SERVER_URL=http://apm.local:8200
ELASTIC_APM_SERVICE_NAME=sec-hello
ELASTIC_APM_ENVIRONMENT=development
ELASTIC_APM_LOG_FILE=stderr
ELASTIC_APM_LOG_LEVEL=debug
```
I'm able to retrieve other env vars such ADDRESS_PORT in the main function.

Also I tried to add to a custom init function:

```go
func init () {

	err := godotenv.Load()
	if err != nil {
		log.Warning("Error loading .env file")
	}

}

func main() {
	/* Starting new Router */
	router := mux.NewRouter()
	apmgorilla.Instrument(router)
	router.Use(apmgorilla.Middleware())
	router.HandleFunc("/hello", helloWorld).Methods("GET")
	addressPort := utils.GetEnv("ADDRESS_PORT", ":8000")
	log.Fatal(http.ListenAndServe(addressPort, router))
}
```
Also with a init assign function:

```go
var hackinit = hackInit()
func hackInit() int {

	err := godotenv.Load()
	if err != nil {
		log.Warning("Error loading .env file")
	}
}

```
Also without luck, the only way that I have to use the APM is exporting  this variables outside the program, there are some way to load that inside the program?

**Comment by axw** [comment] 2019-08-27 01:05
The problem is that the global tracer and transport are initialised before you call that function. This can partially be addressed by calling https://godoc.org/go.elastic.co/apm/transport#InitDefault just after `godotenv.Load`; this will pick up the new value for `ELASTIC_APM_SERVER_URL`.

I say "partially" because the other variables will not be picked up. You could create a new tracer (which will pick up the new environment variable values) and pass that into `Instrument` as an option, like this:

```go
tracer, err := apm.NewTracer("", "")
if err != nil {
    log.Fatal(err)
}
apmgorilla.Instrument(router, apmgorilla.WithTracer(tracer))
```

However... this is still not a complete solution, because the logger won't be updated. I think we should add a new function to reinitialise everything, like:

```go
package apm

// InitEnv will reinitialize apm.DefaultTracer, transport.Default, and the default logger
// using environment variables. You should call this if you update environment variables
// after program startup, e.g. by reading from a file.
//
// If any of the environment variables are invalid, an error will be returned and the
// global variables will be unchanged.
func InitEnv() error
```

What do you think?

By the way: you only need to call `apmgorilla.Instrument(router)` _or_ `router.Use(apmgorilla.Middleware())`, not both. The first one is preferable.

Even though in this case there is a bug, in the future please ask questions at https://discuss.elastic.co/c/apm, for greater visibility. Then we can open a bug if necessary. Thank you!

**Comment by berni69** [comment] 2019-08-27 06:27
Thanks for your response and you suggestions for the moment I can start instrumenting usingInit default, but would be fine to have the function InitEnv on the top of the module to reset all the variables. 

Also I removed the router.Use(apmgorilla.Middleware()) from my code. 

In the next issue I will use the forum. 

Thanks!

**Comment by axw** [comment] 2019-08-27 06:39
Great, thanks for the feedback. I've opened a new issue to track this improvement: https://github.com/elastic/apm-agent-go/issues/618. I'll close this one, please subscribe to that if you'd like to be informed of updates.

**Closed by axw** 2019-08-27 06:39 UTC
