### ISSUE TITLE
Report complete error chains

### ISSUE THREAD

**Issue by liupeidong0620** [elastic/apm-agent-go#423] opened 2019-01-10 10:07 UTC
## Describe the bug
```go
// err   generated by the net/http
apmError := apm.CaptureError(apmCtx, err)
apmError.Send()
```
net err will not execute here, exceptionData.typeName can't get the correct value.
```go
func initException(e *exceptionData, err error) {
     .......
    // Set Module, Type, Attributes, and Code.
    switch err := err.(type) {     // net err 
    case *net.OpError:
        e.typePackagePath, e.typeName = "net", "OpError"
        setAttr("op", err.Op)
        setAttr("net", err.Net)
        setAttr("source", err.Source)
        setAttr("addr", err.Addr)
    ........
}

golang net err relation:

error ----> net.Error ---> net.OpError
                  net.OpError.Err|
                                 |--------> *net.DNSError
                                 |--------> *net.InvaildAddrError
                                 |--------> *net.UnkonwnNetworkError
                                 |---------> *net.AddrError
                                 |---------> *net.DNSConfigError
                                 |---------> *os.SyscallError -----> *os.SyscallError.Err---> sys.Errno
```

This place will affect the error classification. [Please see here](https://github.com/elastic/apm-server/blob/558480cab0d98450658510891f7461c0425d9a8c/processor/error/event.go#L236-L269).I hope to get a more accurate error classification.

**Comment by liupeidong0620** [comment] 2019-01-10 12:15
example
```
func TestErrorsTypeName(t *testing.T) {
	var err error

	client := &http.Client{
		Timeout: 5 * time.Second,
	}
	req, err := http.NewRequest("GET", "http://some.url", nil)
	res, err := client.Do(req)
	if err != nil {
		modelError := sendError(t, err)
		exception := modelError.Exception
		fmt.Println("exception.Type:", exception.Type)
		fmt.Println("exception.Message:", exception.Message)
	} else {
		defer res.Body.Close()
	}
}

=== RUN   TestErrorsTypeName
exception.Type: Error
exception.Message: Get http://some.url: dial tcp: lookup some.url: no such host
--- PASS: TestErrorsTypeName (0.00s)
PASS
ok  	command-line-arguments	(cached)
```
Expectation
```
exception.Type -------> OpError
```

**Comment by liupeidong0620** [comment] 2019-01-10 12:19
@axw

**Comment by axw** [comment] 2019-01-11 01:56
In the case of `net/http` errors, the error type is [*net/url.Error](https://golang.org/pkg/net/url/#Error) (similar to `net.OpError`), not `net.Error` (which is an interface). You can check the error type's package name in the `Exception.Module` field.

In some cases the `net/url.Error` Err field will be a `net.OpError`. Is it useful to set the type name to that? Why is that better?

Ideally we would describe the full error chain like `net/url.Error > net.OpError > net.DNSError`, but that is not currently supported by our model.

**Comment by liupeidong0620** [comment] 2019-01-11 07:06
## Simple example
``` go
package main

import (
	"context"
	"fmt"
	"time"

	"go.elastic.co/apm"
)

type TestError struct {
	When time.Time
	What string
}

func (e TestError) Error() string {
	return fmt.Sprintf("%v: %v", e.When, e.What)
}

type Test1Error struct {
	When time.Time
	What string
}

func (e Test1Error) Error() string {
	return fmt.Sprintf("%v: %v", e.When, e.What)
}

type Test2Error struct {
	When time.Time
	What string
}

func (e Test2Error) Error() string {
	return fmt.Sprintf("%v: %v", e.When, e.What)
}

type Test3Error struct {
	When time.Time
	What string
}

func (e Test3Error) Error() string {
	return fmt.Sprintf("%v: %v", e.When, e.What)
}

func main() {
	var i int

	var err error
	fmt.Println("start ....")
	apmTx := apm.DefaultTracer.StartTransaction("test_transaction", "transaction")
	apmCtx := apm.ContextWithTransaction(context.Background(), apmTx)
	for i < 20 {
		switch i % 4 {
		case 0:
			err = TestError{
				When: time.Now(),
				What: "test0",
			}
		case 1:
			err = Test1Error{
				When: time.Now(),
				What: "test1",
			}
		case 2:
			err = Test2Error{
				When: time.Now(),
				What: "test2",
			}
		case 3:
			err = Test3Error{
				When: time.Now(),
				What: "test3",
			}
		}
		e := apm.CaptureError(apmCtx, err)
		e.Send()
		i++
	}
	apm.DefaultTracer.Flush(nil)
	apmTx.End()
	// apm.DefaultTracer.Close()
	time.Sleep(10 * time.Second)
	fmt.Println("stop ....")
}

```
When collecting errors in the same location, the error classification in kibana is based on `error.grouping_key`, which is generated in relation to `exceptionData.typeName`. [Kibana display](https://github.com/liupeidong0620/temp_picture/blob/master/apm-agent-picture/apm-typeName.jpg)

I hope that the standard error of golang can be divided more carefully.For example: Every error type name in the net library affects the error collection display.

**Comment by liupeidong0620** [comment] 2019-01-11 07:06
@axw

**Comment by axw** [comment] 2019-01-11 07:16
@liupeidong0620 I understand that the error type name is used for grouping.

My question is this: is it really more useful to group these errors under `net.OpError` vs. `net/url.Error`?

I think it might be more useful if we set the type name to the cause of the `net.OpError` or `net/url.Error` error, by traversing the `Err` fields. So in your example in https://github.com/elastic/apm-agent-go/issues/423#issuecomment-453075865, we would set the type name to "DNSError", not "OpError".

What do you think?

**Comment by liupeidong0620** [comment] 2019-01-11 08:09
@axw I don't have a good idea. Your thoughts are not bad.

**Comment by axw** [comment] 2019-01-11 09:58
@liupeidong0620 I'll discuss this with the rest of the agent developers. I would like to solve this by adding support for nested errors, so the grouping key takes into account the root cause. I will report back when we come to some conclusion.

**Comment by axw** [comment] 2019-01-23 09:32
https://github.com/elastic/apm/issues/40

**Comment by axw** [comment] 2019-09-05 07:28
As @Azuka noted in https://github.com/elastic/apm-agent-go/issues/632, we can currently lose important stack trace information when errors are wrapped using github.com/pkg/errors.Wrap. That should be addressed by this issue.

One thing that will require a bit of further thought is how to set the culprit. I think we should probably look at the deepest error that has a non-library frame. Currently we take the deepest non-library frame of the top-most stack.

**Comment by Azuka** [comment] 2019-09-06 02:18
As a stop-gap, I'm using this: https://gist.github.com/Azuka/07bb3797696a6c413419b2b65d58db6e as the full trace is quite important to me.

**Closed** 2019-09-26 07:13 UTC
Labels: [zube]: Backlog
