### ISSUE TITLE
CaptureBodyMode doesn't appear to work as expected

### ISSUE THREAD

**Issue by Jasonfran** [elastic/apm-agent-go#874] opened 2021-01-22 19:10 UTC
**Describe the bug**
Hi, when setting the CaptureBodyMode to CaptureBodyErrors I do not see the request body field populated in Kibana when an error logged through `apm.CaptureError()` or if the HTTP handler returns a 5xx error.

**To Reproduce**
1) Set CaptureBodyMode to CaptureBodyErrors
```go
apm.DefaultTracer.SetCaptureBody(apm.CaptureBodyErrors)
```
2) Return a 5xx error from a HTTP handler
3) Inspect that error in Kibana
4) See that the request body field is not populated
6) Return record an APM error in the handler
7) Inspect that error in Kibana
8) See that the request body field is not populated

**Expected behavior**
I would expect that when I the CaptureBodyMode to CaptureBodyErrors and return a 5xx error, then I would see the error in Kibana and that the request body field is populated.

-----

I did some debugging and found the following:

In https://github.com/elastic/apm-agent-go/blob/master/context.go#L204 

```go
// SetHTTPRequestBody sets the request body in context given a (possibly nil)
// BodyCapturer returned by Tracer.CaptureHTTPRequestBody.
func (c *Context) SetHTTPRequestBody(bc *BodyCapturer) {
	if bc == nil || bc.captureBody&c.captureBodyMask == 0 {
		return
	}
	if bc.setContext(&c.requestBody) {
		c.request.Body = &c.requestBody
	}
}
```

I believe this is the code responsible for deciding whether it's attached or not. I found that `c.captureBodyMask` always seems to be `CaptureBodyTransactions`. 

During an errorred request with CaptureBodyMode set to `CaptureBodyErrors`, `bc.captureBody` will be `CaptureBodyErrors`. And because `CaptureBodyErrors & CaptureBodyTransactions == 0` then no request body is attached. They will only get attached if the CaptureBodyMode is set to `CaptureBodyAll` or `CaptureBodyTransactions`.

This logic seems wrong to me as I believe these are supposed to work like regular bit masks. I would instead expect this to perhaps be:
```go
if bc == nil || bc.captureBody|c.captureBodyMask&CaptureBodyOff == 0 {
```
If `c.captureBodyMask` is intended to be used that way at least. I would submit a PR but I'm not 100% sure this is a bug and I may just be an idiot!

Thanks

**Comment by axw** [comment] 2021-01-25 03:02
@Jasonfran "errors" in this context is not failing HTTP requests, but rather exceptions, panics, etc. If your handler panicked, then CaptureBodyErrors would (should) capture the request body on the resultant error event.

For other 5xx cases, you would need to use CaptureBodyTransactions; but this will capture the request body regardless of the status code. If you don't want to capture the body for other status codes, you would need to remove the field from the documents before they're stored in Elasticsearch, e.g. using the [Elasticsearch "remove" Ingest node processor](https://www.elastic.co/guide/en/elasticsearch/reference/current/remove-processor.html) with a condition on the status code field.

**Comment by Jasonfran** [comment] 2021-01-25 08:57
@axw Oh okay. I expected that 5xx errors weren't supported but I think it's strange than explicitly sending an error through `apm.CaptureError()` also isn't supported. I just checked and indeed panics log the request body.

I couldn't find any documentation that says it's only panics that are supported. Based on wording and the fact that APM errors and panics appear in the same place in Kibana APM, I'd have expected them to work the same. Such that when sending an error through `apm.CaptureError()` that the body is also recorded.

**Comment by axw** [comment] 2021-01-25 09:34
Sorry, I got a bit fixated on the 5xx errors and neglected to address the case of using `apm.CaptureError()`.

For explicit calls to `apm.CaptureError` it is possible but awkward to record the request body. You would need to call `Tracer.CaptureRequestBody`, like in `apmhttp`, and explicitly call the error's `Context.SetHTTPRequestBody` method.

I think what we should do is store the request body capturer (created by apmhttp) in the context, and then `apm.CaptureError` can pull it back out of context in order to store the request body. I have opened https://github.com/elastic/apm-agent-go/issues/877 to address this.

**Comment by axw** [comment] 2021-01-25 09:56
@Jasonfran I'll close this in favour of the more targeted issue #877. If you have any suggestions about how the docs could be clarified in regards to the 5xx errors not capturing the request body (by design), please let us know here or at https://discuss.elastic.co/c/apm. Thanks for opening the issue!

**Closed by axw** 2021-01-25 09:56 UTC
Labels: agent-go
