### ISSUE TITLE
When using configuration using Tracer API, two gathering tasks remains and the first one is not configured correctly

### ISSUE THREAD

**Issue by Sayrus** [elastic/apm-agent-go#770] opened 2020-05-14 16:11 UTC
**Describe the bug**

When using Tracer API to configure the Go Agent, metrics are gathered and sent twice.
This is especially obvious when using both Environment variables and configuration through code, metrics are sent twice with different service_name and metadata.
I know the documentation says only one configuration method should be used but this kind of configuration is used in Thanos as only so many fields are configurable using Thanos tracing.config (see https://thanos.io/tracing.md/).

What seems to happen is that a first metricGatherer is created by `init()`, then a second one is created by `newTracer`.
It seems that both gatherer are alive, gathering and sending metrics.
Obviously, this is rarely a problem as the first gatherer usually has invalid configuration (as the apm-server is usually not on localhost) but it generates `Connection refused` and overhead anyway.

Logs in DEBUG level:
```
"level":"debug","time":"2020-05-14T13:03:40Z","message":"sent request with 42 transactions, 0 spans, 0 errors, 0 metricsets"}
{"level":"debug","time":"2020-05-14T13:03:55Z","message":"sent request with 30 transactions, 54 spans, 0 errors, 0 metricsets"}
{"level":"debug","time":"2020-05-14T13:03:55Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T13:03:55Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T13:04:05Z","message":"sent request with 0 transactions, 0 spans, 0 errors, 1 metricset"}
{"level":"debug","time":"2020-05-14T13:04:05Z","message":"sent request with 30 transactions, 54 spans, 0 errors, 7 metricsets"}
{"level":"debug","time":"2020-05-14T13:04:15Z","message":"sent request with 29 transactions, 27 spans, 0 errors, 0 metricsets"}
{"level":"debug","time":"2020-05-14T13:04:25Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T13:04:25Z","message":"gathering metrics"}
{"level":"debug","time":"2020-05-14T13:04:25Z","message":"sent request with 42 transactions, 0 spans, 0 errors, 7 metricsets"}
{"level":"debug","time":"2020-05-14T13:04:35Z","message":"sent request with 0 transactions, 0 spans, 0 errors, 1 metricset"}
{"level":"debug","time":"2020-05-14T13:04:40Z","message":"sent request with 29 transactions, 27 spans, 0 errors, 0 metricsets"}
{"level":"debug","time":"2020-05-14T13:04:50Z","message":"sent request with 30 transactions, 0 spans, 0 errors, 0 metricsets"}
```

As far as my current understanding of the problems goes, the bug is something like this:
- Elastic APM Go Agent enables metrics by default (`init()` from `tracer.go`). The default configuration is applied and overridden by environment variables.
- Thanos (or anyone else) then configure the tracer with the `Tracer API` which lead to a new metric gathering task with proper configuration (Actually both options and environment variables)
- Both gathering tasks continue to exist and work

**To Reproduce**
Configuration:
I am using Thanos `quay.io/thanos/thanos:v0.12.2` with the following configuration:
```
        --tracing.config=type: ELASTIC_APM
        config:
          service_name: "thanos-query"
          service_version: "1.0.0"
          service_environment: "staging-1"
          sample_rate: 1
```
Full command-line can be found later in **ingested documents**
This initialize the tracer with the right configuration (see: https://github.com/thanos-io/thanos/blob/master/cmd/thanos/main.go#L154 and https://github.com/thanos-io/thanos/blob/master/pkg/tracing/elasticapm/elastic_apm.go for more the calls made to initialize the Elastic APM Go Agent)

Additionally, you might need to configure these if you want to send somewhere else than localhost:
- `ELASTIC_APM_SERVER_URL`
- `ELASTIC_APM_SECRET_TOKEN`

Call:
Start Thanos Query and you're done. You now have metrics coming from:
- `thanos`: This name is automatically taken from the binary name. This metric gatherer works without any code configuration (service_version, service_environment are all missing from the final document) but use environment variables [1] (endpoint is correct, modification made using environment are visible in ES). I'd say this is the MetricGatherer created by `init()` in `tracer.go`.
- `thanos-query` with the proper configuration. This is the one created when calling `newTracer` with proper options.

[1] To make this obvious, you can add the following env variables:
`ELASTIC_APM_SERVICE_NAME`: thanos-query-from-env
This will lead to the invalid metric being sent with `thanos-query-from-env` instead of `thanos` but won't have any impact on the `thanos-query` metrics.

**Example of ingested documents**
```json
{
  "_index": "apm-7.7.0-metric-000001",
  "_type": "_doc",
  "_id": "QMVjE3IBpjoDB9rm0G6M",
  "_version": 1,
  "_score": null,
  "_source": {
    "container": {
      "id": "same on both json"
    },
    "observer": {
      "hostname": "my-apm-server",
      "id": "same on both json",
      "ephemeral_id": "same on both json",
      "type": "apm-server",
      "version": "7.7.0",
      "version_major": 7
    },
    "agent": {
      "name": "go",
      "version": "1.5.0"
    },
    "process": {
      "args": [
        "/bin/thanos",
        "query",
        "--log.level=debug",
        "--log.format=logfmt",
        "--grpc-address=0.0.0.0:10901",
        "--http-address=0.0.0.0:10902",
        "--query.replica-label=replica",
        "--query.auto-downsampling",
        "--store.sd-dns-resolver=miekgdns",
        "--store=dnssrv+_grpc._tcp.thanos-store-grpc.ns.svc.cluster.local",
        "--store=dnssrv+_grpc._tcp.thanos-sidecar-grpc.ns.svc.cluster.local",
        "--store.sd-interval=5m",
        "--http-grace-period=30s",
        "--grpc-grace-period=30s",
        "--query.max-concurrent=300",
        "--query.timeout=1m",
        "--store.response-timeout=45s",
        "--tracing.config=type: ELASTIC_APM\nconfig:\n  service_name: \"thanos-query\"\n  service_version: \"1.0.0\"\n  service_environment: \"staging-1\"\n  sample_rate: 1\n"
      ],
      "pid": 1,
      "title": "thanos",
      "ppid": 0
    },
    "@timestamp": "2020-05-14T13:33:17.073Z",
    "ecs": {
      "version": "1.5.0"
    },
    "service": {
      "node": {
        "name": "same on both json"
      },
      "name": "thanos-query-from-env",
      "runtime": {
        "name": "gc",
        "version": "go1.13.1"
      },
      "language": {
        "name": "go",
        "version": "go1.13.1"
      }
    },
    "golang": {
      "goroutines": 82,
      "heap": {
        "system": {
          "total": 73072888,
          "stack": 1572864,
          "obtained": 65536000,
          "released": 46145536
        },
        "allocations": {
          "total": 25834968,
          "frees": 73241,
          "idle": 46145536,
          "objects": 69670,
          "active": 19390464,
          "mallocs": 142911,
          "allocated": 17817192
        },
        "gc": {
          "next_gc_limit": 23264160,
          "total_count": 5,
          "total_pause": {
            "ns": 619196
          },
          "cpu_fraction": 0.0055473759973988564
        }
      }
    },
    "host": {
      "hostname": "same on both json",
      "os": {
        "platform": "linux"
      },
      "ip": "<redacted>",
      "name": "same on both json",
      "architecture": "amd64"
    },
    "processor": {
      "name": "metric",
      "event": "metric"
    }
  },
  "fields": {
    "@timestamp": [
      "2020-05-14T13:33:17.073Z"
    ]
  }
}
```

```json
{
  "_index": "apm-7.7.0-metric-000001",
  "_type": "_doc",
  "_id": "RsVjE3IBpjoDB9rmqWqg",
  "_version": 1,
  "_score": null,
  "_source": {
    "container": {
      "id": "same on both json"
    },
    "observer": {
      "hostname": "my-apm-server",
      "id": "same on both json",
      "ephemeral_id": "same on both json",
      "type": "apm-server",
      "version": "7.7.0",
      "version_major": 7
    },
    "agent": {
      "name": "go",
      "version": "1.5.0"
    },
    "process": {
      "args": [
        "/bin/thanos",
        "query",
        "--log.level=debug",
        "--log.format=logfmt",
        "--grpc-address=0.0.0.0:10901",
        "--http-address=0.0.0.0:10902",
        "--query.replica-label=replica",
        "--query.auto-downsampling",
        "--store.sd-dns-resolver=miekgdns",
        "--store=dnssrv+_grpc._tcp.thanos-store-grpc.ns.svc.cluster.local",
        "--store=dnssrv+_grpc._tcp.thanos-sidecar-grpc.ns.svc.cluster.local",
        "--store.sd-interval=5m",
        "--http-grace-period=30s",
        "--grpc-grace-period=30s",
        "--query.max-concurrent=300",
        "--query.timeout=1m",
        "--store.response-timeout=45s",
        "--tracing.config=type: ELASTIC_APM\nconfig:\n  service_name: \"thanos-query\"\n  service_version: \"1.0.0\"\n  service_environment: \"staging-1\"\n  sample_rate: 1\n"
      ],
      "pid": 1,
      "title": "thanos",
      "ppid": 0
    },
    "@timestamp": "2020-05-14T13:33:17.098Z",
    "ecs": {
      "version": "1.5.0"
    },
    "service": {
      "node": {
        "name": "same on both json"
      },
      "environment": "staging-1",
      "name": "thanos-query",
      "runtime": {
        "name": "gc",
        "version": "go1.13.1"
      },
      "language": {
        "name": "go",
        "version": "go1.13.1"
      },
      "version": "1.0.0"
    },
    "golang": {
      "goroutines": 83,
      "heap": {
        "system": {
          "total": 73072888,
          "stack": 1572864,
          "obtained": 65536000,
          "released": 45989888
        },
        "allocations": {
          "total": 25981672,
          "frees": 73396,
          "idle": 45989888,
          "objects": 70211,
          "active": 19546112,
          "mallocs": 143607,
          "allocated": 17963896
        },
        "gc": {
          "next_gc_limit": 23264160,
          "total_count": 5,
          "total_pause": {
            "ns": 619196
          },
          "cpu_fraction": 0.0055473759973988564
        }
      }
    },
    "host": {
      "hostname": "same on both json",
      "os": {
        "platform": "linux"
      },
      "ip": "<redacted>",
      "name": "same on both json",
      "architecture": "amd64"
    },
    "processor": {
      "name": "metric",
      "event": "metric"
    }
  },
  "fields": {
    "@timestamp": [
      "2020-05-14T13:33:17.098Z"
    ]
  }
}

```

**Minimal steps to reproduce**
Obviously you guys don't want the hassle of running Thanos to find the bug.
⚠️ I don't guarantee these step will reproduce. ⚠️ 

- Import Elastic APM Go Agent (this should execute `init()` and create a first gathering task)
- Configure a newTracer using `apm.newTracerOptions`

if everything goes well, you now have two gathering tasks.

**Expected behavior**

- Metrics should not be automatically gathered as software can implement support for several agents / tracers. While it seems like a good idea for software implementing several tracers, this is an additional step for the everyone else.
- When configuring a new tracer, it should destroy/update the old builtinMetricGatherer and avoid sending metrics with invalid configuration

I don't think the first behavior cover the case where `newTracerOptions` is called several time.

Best regards,

**Comment by axw** [comment] 2020-05-15 01:21
Thanks for the detailed issue.

> Metrics should not be automatically gathered as software can implement support for several agents / tracers. While it seems like a good idea for software implementing several tracers, this is an additional step for the everyone else.

I'm not sure I understand. I would say applications having support for multiple tracers is not the norm, so I don't think we should optimise for that use case.

The API is designed to make instrumenting Go applications as simple as possible, for typical web services. This means a little (but only a little) more work is required for more complex use cases such as in Thanos.

> When configuring a new tracer, it should destroy/update the old builtinMetricGatherer and avoid sending metrics with invalid configuration

Tracers are independent by design, so creating a tracer should not interfere with another one. In theory you might want to trace multiple, logically independent "services" that are running in the same process. Doing that would prevent such use cases.

What we should _definitely_ do is make it clear in the NewTracer/NewTracerOptions API docs that there is a default tracer which should be closed if it's not needed.

**Comment by axw** [comment] 2020-05-15 01:35
> Tracers are independent by design, so creating a tracer should not interfere with another one. In theory you might want to trace multiple, logically independent "services" that are running in the same process. Doing that would prevent such use cases.

On the other hand, perhaps we could default to closing `apm.DefaultTracer` when `apm.NewTracer` is called, with an option (bool in TracerOptions) for keeping DefaultTracer active. This change would have to be made in a major version bump. Does that sound reasonable to you?

**Comment by Sayrus** [comment] 2020-05-15 06:50
> 
> I'm not sure I understand. I would say applications having support for multiple tracers is not the norm, so I don't think we should optimise for that use case.
> 

This was in the expected behavior as it "could be expected". I didn't properly express that "everyone else" was the majority of the APM Agent Users.

> Tracers are independent by design, so creating a tracer should not interfere with another one. In theory you might want to trace multiple, logically independent "services" that are running in the same process. Doing that would prevent such use cases.
> 

I did not think about the case where have several tracers on purpose. Thanks for pointing that ouput.

> What we should _definitely_ do is make it clear in the NewTracer/NewTracerOptions API docs that there is a default tracer which should be closed if it's not needed.

I think your PR do that perfectly.

> 
> On the other hand, perhaps we could default to closing `apm.DefaultTracer` when `apm.NewTracer` is called, with an option (bool in TracerOptions) for keeping DefaultTracer active. This change would have to be made in a major version bump. Does that sound reasonable to you?

That's actually a very interesting proposition. While it does make sense to keep several tracers that were called using `apm.NewTracer`, closing the default tracer sounds like a great idea.
You might want more feedback than mine on this.

**Comment by axw** [comment] 2020-05-15 07:51
> I think your PR do that perfectly. We might want to a small warning about it in the Set up the Agent page.

Good idea, will do.

> That's actually a very interesting proposition. While it does make sense to keep several tracers that were called using apm.NewTracer, closing the default tracer sounds like a great idea.
You might want more feedback than mine on this.

I've created a new issue (#773) to consider this change. I'll close this issue now. Thanks again.

**Closed by axw** 2020-05-15 07:51 UTC
