### ISSUE TITLE
Update apm aws module to support aws sdk v2

### ISSUE THREAD

**Issue by senpathi** [elastic/apm-agent-go#1305] opened 2022-09-04 15:10 UTC
After releasing aws sdk v2 for golang, The [session](https://docs.aws.amazon.com/sdk-for-go/api/aws/session) package and associated functionality are replaced with a simplified configuration system provided by the [config](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config) package.

As mention in the [SDK documentation,](https://aws.github.io/aws-sdk-go-v2/docs/migrating/#configuration-loading)
> The [session](https://docs.aws.amazon.com/sdk-for-go/api/aws/session) package and associated functionality are replaced with a simplified configuration system provided by the [config][config](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config) package. The config package is a separate Go module, and can be included in your applications dependencies by with go get.
> 
> go get github.com/aws/aws-sdk-go-v2/config
> The [session.New](https://docs.aws.amazon.com/sdk-for-go/api/aws/session#New), [session.NewSession](https://docs.aws.amazon.com/sdk-for-go/api/aws/session#NewSession), [NewSessionWithOptions](https://docs.aws.amazon.com/sdk-for-go/api/aws/session#NewSessionWithOptions), and [session.Must](https://docs.aws.amazon.com/sdk-for-go/api/aws/session#Must) must be migrated to [config.LoadDefaultConfig](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config#LoadDefaultConfig).
> 
> The config package provides several helper functions that aid in overriding the shared configuration loading programmatically. These function names are prefixed with With followed by option that they override. Let’s look at some examples of how to migrate usage of the session package.
> 
> For more information on loading shared configuration see [Configuring the AWS SDK for Go V2](https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/).

So, we couldn't use [apm aws module](https://www.elastic.co/guide/en/apm/agent/go/current/builtin-modules.html#builtin-modules-apmawssdkgo) for golang applications which are using was adk v2.

I am requesting an update for apm aws module to support updates from aws SDK 2.

**Comment by axw** [comment] 2022-09-05 02:21
This is a duplicate of https://github.com/elastic/apm-agent-go/issues/1235, so I'll close this one. Please subscribe to the other issue. If you're interested in contributing, we would be happy to review PRs. Otherwise - your interest in this is noted :)

**Closed by axw** 2022-09-05 02:21 UTC
Labels: agent-go
